services:
  base:
    build:
      context: ./docker/base
      tags:
        - "linhbngo/csc466:base-latest"

  head:
    build:
      context: ./docker/master
      tags:
        - "linhbngo/csc466:head-latest"
    image: linhbngo/csc466:head-latest
    ports:
      - "18088:8088"
      - "18000:8000"
      - "2222:22"
    volumes:
      - ../courses:/lectures # courses is a github repo containing lecture materials
      - ../csc466data:/data
      - ./home:/home
    expose:
      - "22"
    hostname: head
    container_name: head
    networks:
      - compute

  compute01:
    build:
      context: ./docker/worker
      tags:
        - "linhbngo/csc466:compute-latest"
    init: true
    image: linhbngo/csc466:compute-latest
    volumes:
      - ../courses:/lectures # courses is a github repo containing lecture materials
      - ../csc466data:/data
      - ./home:/home
    expose:
      - "22"
    hostname: compute01
    container_name: compute01
    networks:
      - compute

  compute02:
    build:
      context: ./docker/worker
      tags:
        - "linhbngo/csc466:compute-latest"
    init: true
    image: linhbngo/csc466:compute-latest
    volumes:
      - ../courses:/lectures # courses is a github repo containing lecture materials
      - ../csc466data:/data
      - ./home:/home
    expose:
      - "22"
    hostname: compute02
    container_name: compute02
    networks:
      - compute
      
networks:
  compute:
    name: compute
