services:
  head:
    image: head:latest
    ports:
      - "8888:8888"
      - "8088:8088"
      - "8000:8000"
      - "22:22"
    volumes:
      - ../courses:/lectures # courses is a github repo containing lecture materials
      - ../csc466data:/data
      - software:/software
      
  compute:
    image: compute:latest
    volumes:
      - ../courses:/lectures # courses is a github repo containing lecture materials
      - ../csc466data:/data
      - software:/software
      
networks:
  default:
    driver: bridge
