services:
  base:
    build:
      context: ./docker/base
      tags:
        - "linhbngo/csc466:base-latest"
  head:
    build:
      context: ./docker/master
      tags:
        - "linhbngo/csc466:head-latest"
    image: linhbngo/csc466:head-latest
    ports:
      - "18088:8088"
      - "18000:8000"
      - "2222:22"
    volumes:
      - ../courses:/lectures # courses is a github repo containing lecture materials
      - ../csc466data:/data
    expose:
      - "22"
  compute:
    build:
      context: ./docker/worker
      tags:
        - "linhbngo/csc466:compute-latest"
    image: linhbngo/csc466:compute-latest
    volumes:
      - ../courses:/lectures # courses is a github repo containing lecture materials
      - ../csc466data:/data
      
networks:
  default:
    driver: bridge
